<?php

/**
* @file
* Contains hooks for guestbook module.
*/

module_load_include('inc', 'guestbook', 'include/guestbook.form');
module_load_include('inc', 'guestbook', 'include/guestbook.core');
module_load_include('inc', 'guestbook', 'include/guestbook.theme');

/**
 * URL for downloading xml weather file.
 */
define('GUESTBOOK_WEATHER_URL', 'https://xml.meteoservice.ru/export/gismeteo/point/2897.xml');

/**
 * Implements hook_permission().
 */
function guestbook_permission() {
  return array(
    'access guestbook messages' => array(
      'title' => t('Show messages for the Guestbook module'),
    ),
    'access guestbook content' => array(
      'title' => t('Access to edit and delete for the Guestbook module'),
    ),
  );
}

/**
* Implements hook_menu(). 
*/
function guestbook_menu() {
  // Main page.
  $items['guestbook-page'] = array(
    'title' => 'Guestbook',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('guestbook_page_form'),
    'access arguments' => array('access guestbook messages'),
  );
  // Edit message.
  $items['guestbook-page/%guestbook_mid/edit'] = array(
    'title' => 'Guestbook',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('guestbook_page_form', 1),
    'access arguments' => array('access guestbook content'),
  );
  // Delete message.
  $items['guestbook-page/%guestbook_mid/delete'] = array(
    'title' => 'Delete message',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('guestbook_message_form_delete', 1),
    'access arguments' => array('access guestbook content'),
  );

  return $items;
}

/**
 * Loads a message info.
 *
 * @param $mid
 *   Integer specifying the message id to load.
 *
 * @return array
 *   A fully-loaded array of message info ('id', 'uid', 'sid', 'date', 'message').
 *   - id: message id;
 *   - uid: user id;
 *   - sid: session id;
 *   - date: message creation date;
 *   - message: message text.
 */
function guestbook_mid_load($mid) {
  return guestbook_info_by_mid($mid);
}

/*
 * Implements hook_cron().
 */
function guestbook_cron() {
  guestbook_get_xml_weather();
}

/*
 * Implements hook_block_info().
 */
function guestbook_block_info() {
  // Build weather block.
  $blocks['weather'] = array(
    'title' => t('Weather in Vitebsk'),
    'info' => t('The Weather'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    'status' => TRUE,
    'weight' => -10,
  );

  return $blocks;
}

/*
 * Implements hook_block_view().
 */
function guestbook_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'weather':
      $block['subject'] = t('Vitebsk Weather');
      $block['content'] = array(
        '#markup' => theme('guestbook_weather_template',
          array(
            'weather' => guestbook_weather(),
          )
        ),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'guestbook') . '/css/guestbook.css',
          ),
        )
      );
      break;
  }

  return $block;
}

/*
 * Implements hook_theme().
 */
function guestbook_theme() {
  return array(
    'guestbook_message_template' => array(
      'variables' => array(
        'body' => NULL,
      ),
      'template' => 'templates/guestbook_message_template',
    ),
    'guestbook_weather_template' => array(
      'variables' => array(
        'weather' => NULL,
      ),
      'template' => 'templates/guestbook_weather_template',
    ),
  );
}
