<?php

/**
* @file
* Build page for guestbook and weather block.
*/

module_load_include('inc', 'guestbook', 'include/guestbook.form');
module_load_include('inc', 'guestbook', 'include/guestbook.core');

/**
 * Implements hook_permission().
 */
function guestbook_permission() {
  return array(
    'access guestbook messages' => array(
      'title' => t('Show messages for the Guestbook module'),
    ),
    'access guestbook content' => array(
      'title' => t('Access to edit and delete for the Guestbook module'),
    ),
  );
}

/**
* Implements hook_menu(). 
*/
 function guestbook_menu() {
   // Main page.
   $items['guestbook-page'] = array(
     'title' => 'Guestbook',
     'page callback'   => 'drupal_get_form',
     'page arguments'  => array('guestbook_page_form'),
     'access arguments' => array('access guestbook messages'),
     'type' => MENU_NORMAL_ITEM,
  );
   // Edit message.
   $items['guestbook-page/%guestbook_mid/edit'] = array(
     'title'            => 'Guestbook',
     'page callback'    => 'drupal_get_form',
     'page arguments'   => array('guestbook_page_form', 1),
     'access arguments' => array('access guestbook content'),
     'type' => MENU_NORMAL_ITEM,

   );
   // Delete message.
   $items['guestbook-page/%guestbook_mid/delete'] = array(
     'title'            => 'Delete message',
     'page callback'    => 'guestbook_message_delete',
     'page arguments'   => array(1),
     'access arguments' => array('access guestbook content'),
     'type' => MENU_NORMAL_ITEM,
   );

   return $items;
}

/**
 * Loads a message info.
 *
 * @param $mid
 *   Integer specifying the message id to load.
 * @return
 *   A fully-loaded array of message info ('id', 'uid', 'sid', 'date', 'message').
 *   id - message id; uid - user id; sid - session id; date - message creation
 *   date; message - message text.
 */
function guestbook_mid_load($mid) {
  $query = db_select('guestbook_drupal', 't')
    ->fields('t', array('id', 'uid', 'sid', 'date', 'message'))
    ->condition('t.id', $mid)
    ->execute();
  $value = $query->fetchAssoc();

  return $value;
}

/*
 * Implements hook_cron().
 */
function guestbook_cron() {
  guestbook_get_xml_weather();
}

/*
 * Implements hook_block_info().
 */
function guestbook_block_info() {
  // Build weather block.
  $blocks['weather'] = array(
    'title' => t('Weather in Vitebsk'),
    'info' => t('The Weather'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    'status' => TRUE,
    'weight' => -10,
  );

  return $blocks;
}

/*
 * Implements hook_block_view().
 */
function guestbook_block_view($delta = '') {
  $block = [];
  switch($delta){
    case 'weather':
      $block['subject'] = t('Vitebsk Weather');
      $block['content'] = theme('guestbook_weather_template', array(
        'weather' => guestbook_weather(),
          )
      );
      break;
  }

  return $block;
}

/*
 * Implements hook_theme().
 */
function guestbook_theme() {
  return array(
    'guestbook_message_template' => array(
      'variables' => array(
        'body' => NULL,
      ),
      'template' => 'template/guestbook_message_template',
    ),
    'guestbook_weather_template' => array(
      'variables' => array(
        'weather' => NULL,
      ),
      'template' => 'template/guestbook_weather_template',
    ),
  );
}
